all:
  children:
    frontend:
      hosts:
        frontend-server:
          ansible_host: frontend-server
          ansible_user: root
          server_type: frontend

    backend:
      hosts:
        backend-server:
          ansible_host: backend-server
          ansible_user: root
          server_type: backend

    quiz_master:
      children:
        frontend:
        backend:
      vars:
        # Variables communes
        docker_compose_version: "2.21.0"
        nginx_version: "1.24"
        app_name: "quiz-master"
        app_user: "quizmaster"
        app_directory: "/opt/quiz-master"

        # Container Registry
        registry_url: "{{ registry }}"
        registry_username: "{{ github_actor }}"
        registry_password: "{{ github_token }}"

        # Images
        frontend_image: "{{ frontend_image }}"
        backend_image: "{{ backend_image }}"

        # Networking
        frontend_port: 3000
        backend_port: 8003
        nginx_port: 80
        ssl_port: 443

        # Server IPs for cross-server communication
        frontend_server_ip: "{{ lookup('env', 'FRONTEND_SERVER_IP') | default(hostvars['frontend-server']['ansible_host']) }}"
        backend_server_ip: "{{ lookup('env', 'BACKEND_SERVER_IP') | default(hostvars['backend-server']['ansible_host']) }}"

        # Environment
        node_env: "production"
        log_level: "info"
